# Using spring-ai-mcp-server-webflux-spring-boot-starter
spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        sse-message-endpoint: /mcp/message